export const stackCollaboLists = [
	{
		projectName: "BBappy",
		date: "2022.07 ~ ing",
		service: "동아리 홈페이지",
		position: "퍼블리싱 / 프론트엔드 개발",
		type: "develop",
		tag: ["# Next.js", "# Typescript", "# scss"],
		imgUrl: "/images/portfolio/bbappy.png",
		skill: ["# Next.js", "# Typescript", "# scss", "# Bootstrap"],
		summaryDescription: "개발 동아리 홈페이지 입니다.",
		mainDescription: [
			"- 요구사항 도출 및 화면 설계",
			"- 사용자 권한 별 관리 기능 제공",
			"- 클라이언트 접속 지연시간 튜닝(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		githubLink: "",
	},
	{
		projectName: "Viodio ",
		date: "2022.02 - 2022.03",
		position: "퍼블리싱 / 프론트엔드 개발",
		service: "음원 서비스",
		type: "develop",
		tag: ["# Next.js", "# Typescript", "# css"],
		imgUrl: "/images/portfolio/viodio.png",
		skill: [
			"# Next.js ",
			"# Typescript ",
			"# css ",
			"# Bootstrap ",
			"# Antdesign ",
			"# Reactstrap ",
			"# Redux ",
			"# swiper",
		],
		summaryDescription: "음원 서비스입니다.",
		mainDescription: [
			"- 요구사항 도출 및 화면 설계",
			"- 라이브러리 버그 수정 및 UI 수정",
			"- QA 사항 수정 보완",
			"- API 를 가지고 클라이언트 개발",
			"- 클라이언트 접속 지연시간 개선(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		githubLink: "",
	},
	{
		projectName: "Stela",
		date: "2021.09 - 2022.02",
		service: "음원 서비스",
		position: "퍼블리싱 / 프론트엔드 개발",
		type: "develop",
		tag: ["# Next.js", "# Typescript", "# css"],
		imgUrl: "/images/portfolio/stela.png",
		skill: [
			"# Next.js",
			"# Typescript",
			"# scss",
			"# Bootstrap",
			"# styled-component ",
			"# material-ui",
			"# next-i18",
			"# redux-toolkit",
			"# Formik",
			"# js-cookie",
			"# axios ",
		],
		summaryDescription: "음원 서비스입니다.",
		mainDescription: [
			"- 홈페이지 요구사항 구축 및 화면 설계 및 기능 구현",
			"- 어드민 관리 페이지 화면 구축 및 기능 구현",
			"- next-i18 다국어 영문/한국어 적용",
			"- API 를 가지고 클라이언트 개발",
			"- Redux로 형상관리",
			"- 클라이언트 접속 지연시간 개선(메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		githubLink: "",
	},
	{
		projectName: "방구석연구소",
		date: "2021.07 _  2021.0",
		service: "유형테스트 서비스",
		position: "퍼블리싱",
		type: "develop",
		tag: ["# Next.js", "# Typescript", "# css"],
		imgUrl: "/images/portfolio/metav.png",
		skill: [
			"# Next.js ",
			"# Typescript ",
			"# css ",
			"# Bootstrap ",
			"# Reactstrap ",
			"# Mui ",
			"# chart.js",
		],
		summaryDescription: "유형테스트 서비스입니다.",
		mainDescription: [
			"- 홈페이지 요구사항 구축 및 화면 설계 및 기능 구현",
			"- 어드민 관리 페이지 화면 구축 및 기능 구현",
			"- UI 버그 수정 및 기능 구현 ",
		],
		serviceLink: "https://www.banggooso.com/",
		githubLink: "",
	},
	{
		projectName: "DTX / CNT",
		date: "2021.07 _ 2주소요",
		service: "환자 관리차트 의사 대시보드",
		position: "퍼블리싱",
		type: "develop",
		tag: ["# React-native", "# css"],
		imgUrl: "/images/portfolio/CNTDTX.png",
		skill: [
			"# React-native",
			"# Date-picker",
			"# Swiper",
			"# Styled-components",
			"# chart.js",
			"# i18n",
		],
		summaryDescription: "뱡원환자 관리 및 차트 대시보드 서비스입니다.",
		mainDescription: [
			"- 홈페이지 요구사항 구축 및 화면 설계 및 기능 구현",
			"- 관리 페이지 화면 구축 및 기능 구현",
			"- UI 라이브러리 버그 수정 및 기능 구현 ",
			"- i-18n 다국어 영문/한글 적용 ",
		],
		serviceLink: "",
		githubLink: "",
	},
	{
		projectName: "EWORLD",
		date: "2021.05 _ 디자인/기획 3일 + 코딩작업 12일",
		service: [
			"반응형   ※ 본 사이트는 상업적 목적이 아닌 개인 포트폴리오 용도로 만들어 졌습니다. ※",
		],
		position: "퍼블리싱",
		type: "develop",
		tag: ["# html", "# css", "# javascript"],
		imgUrl: "/images/portfolio/Eworld.png",
		skill: ["# html", "# css", "# javascript", "# slick"],
		summaryDescription: " 반응형 개인 포트폴리오용",
		mainDescription: [
			"- 기존 정적인 디자인을 반응형으로 직접 디자인 제작",
			"- 모바일버전과 웹사이트 버전이 나눠있는 것을 반응형으로 새롭게 디자인",
			"- 이월드의 대표색상을 활용하여 한 눈에 사로잡을 수 있으며 놀이공원의 특성을 고려한 이해하기 쉬운 구조의 UI, 경험을 기반으로 사용성과 편리성을 고려한 UX의 웹 사이트를 구성하였고 그 기반으로 코딩",
			"- 놀이공원 시설 검색을 할때  검색키워드에 따라 데이터가 나올 수 있도록 구현",
			"- 페이지스크롤에 따른 동적 라이브러리 구현",
			"- slick 배너 제작",
		],
		serviceLink: "http://breathin62.com/E-WORLD/E-world_main.html",
		githubLink: "https://github.com/KWONSUMIN602/PF_eworld",
	},
	{
		projectName: "SHAKE SHACK",
		date: "2021.05 _ 디자인/기획 2일 + 코딩작업 10일",
		service: [
			"반응형   ※ 본 사이트는 상업적 목적이 아닌 개인 포트폴리오 용도로 만들어 졌습니다. ※",
		],
		position: "퍼블리싱",
		type: "develop",
		tag: ["# html", "# css", "# javascript"],
		imgUrl: "/images/portfolio/shakeshack.png",
		skill: ["# html", "# css", "# javascript"],
		summaryDescription: "클론코딩 개인 포트폴리오용",
		mainDescription: [
			"- 기존 정적인 디자인을 반응형으로 직접 디자인 제작",
			"- 반응형사이트로 모바일/태블릿/pc버전으로 브레이크 포인트를 주어 새롭게 디자인",
			"- 쉑쉑버거의 대표색상을 활용하고 이해하기 쉬운 구조의 UI, 경험을 기반으로 사용성과 편리성을 고려한 UX의 웹 사이트를 구성하였고 그 기반으로 코딩",
			"- 쉑쉑버거 메뉴를 쉽게 볼 수 있도록 셀렉트 박스 / 체크박스로 구현",
			"- 스크롤시 빠른 메뉴 생성구현",
		],
		serviceLink: "http://breathin62.com/shakeshack/shake_shack.html",
		githubLink: "https://github.com/KWONSUMIN602/PF_Shakeshack",
	},
	{
		projectName: "WONDER WALL",
		date: "2021.04 _ 코딩작업 5일",
		service: [
			"클론 코딩   ※ 본 사이트는 상업적 목적이 아닌 개인 포트폴리오 용도로 만들어 졌습니다. ※",
		],
		position: "퍼블리싱",
		type: "develop",
		tag: ["# html", "# css", "# javascript"],
		imgUrl: "/images/portfolio/wonderwall.png",
		skill: ["# html", "# css", "# javascript"],
		summaryDescription: "클론코딩 개인 포트폴리오용",
		mainDescription: [
			"- 기존에 있던 웹사이트를 클론 코딩으로 제작하였습니다.",
			"- 반응형사이트로 모바일/태블릿/pc버전으로 브레이크 포인트를 나눴습니다.",
			"- 또한 웹접근성, 웹표준에 맞는 마크업을 구현하였습니다.",
		],
		serviceLink: "http://breathin62.com/wonderwall/wonderwall.html",
		githubLink: "https://github.com/KWONSUMIN602/PF_wonderwall",
	},
];
