export const stackCollaboLists = [
	{
		projectName: "쿠팡 ",
		date: "2021.02.14 - 2021.04",
		service: "온라인 쇼핑몰",
		type: "develop",
		tag: ["# 태그", "# 태그", "# 태그"],
		imgUrl: "",
		skill: [
			"# React.js",
			"# Flask",
			"# uWsgi",
			"# NginX",
			"# MongoDB",
			"# AWS EC2, S3",
			"# Docker",
			"# NLP (Pytorch, KcBert)",
		],
		summaryDescription: "설명입니다.",
		mainDescription: [
			"- 분석 단계 - 요구사항 도출 및 화면 설계",
			"- 설계 단계 - 화면 설계를 통한 자료 사전 및 도메인 정의, ERD작성",
			"- 학습 플랫폼(물음표 학교, 느낌표 학교) 개발",
			"- 나눔 플랫폼(재능기부) 개발",
			"- 강사 관리 시스템 개발",
			"- 통합 예약시스템(징검다리교실) 개발",
			"- 시멘틱(의미 기반) 검색/분석 시스템 구축(Konan Search 솔루션 사용)",
			"- 사용자 권한 별 관리 기능 제공",
			"- 클라이언트 접속 지연시간 튜닝(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		githubLink: "",
	},
	{
		projectName: "비오디오 ",
		service: "음원 서비스",
		type: "develop",
		tag: ["# 태그", "# 태그", "# 태그"],
		imgUrl: "",
		skill: [
			"# React.js",
			"# Flask",
			"# uWsgi",
			"# NginX",
			"# MongoDB",
			"# AWS EC2, S3",
			"# Docker",
			"# NLP (Pytorch, KcBert)",
		],
		summaryDescription: "설명입니다.",
		mainDescription: [
			"- 분석 단계 - 요구사항 도출 및 화면 설계",
			"- 설계 단계 - 화면 설계를 통한 자료 사전 및 도메인 정의, ERD작성",
			"- 학습 플랫폼(물음표 학교, 느낌표 학교) 개발",
			"- 나눔 플랫폼(재능기부) 개발",
			"- 강사 관리 시스템 개발",
			"- 통합 예약시스템(징검다리교실) 개발",
			"- 시멘틱(의미 기반) 검색/분석 시스템 구축(Konan Search 솔루션 사용)",
			"- 사용자 권한 별 관리 기능 제공",
			"- 클라이언트 접속 지연시간 튜닝(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		githubLink: "",
	},
	{
		projectName: "방구석 연구소",
		service: "성향 분석 서비스",
		type: "develop",
		tag: ["# 태그", "# 태그", "# 태그"],
		imgUrl: "",
		skill: [
			"# React.js",
			"# Flask",
			"# uWsgi",
			"# NginX",
			"# MongoDB",
			"# AWS EC2, S3",
			"# Docker",
			"# NLP (Pytorch, KcBert)",
		],
		summaryDescription: "설명입니다.",
		mainDescription: [
			"- 분석 단계 - 요구사항 도출 및 화면 설계",
			"- 설계 단계 - 화면 설계를 통한 자료 사전 및 도메인 정의, ERD작성",
			"- 학습 플랫폼(물음표 학교, 느낌표 학교) 개발",
			"- 나눔 플랫폼(재능기부) 개발",
			"- 강사 관리 시스템 개발",
			"- 통합 예약시스템(징검다리교실) 개발",
			"- 시멘틱(의미 기반) 검색/분석 시스템 구축(Konan Search 솔루션 사용)",
			"- 사용자 권한 별 관리 기능 제공",
			"- 클라이언트 접속 지연시간 튜닝(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		githubLink: "",
	},
	{
		projectName: "스텔라",
		service: "음원 서비스",
		type: "develop",
		tag: ["# Tag", "# Tag", "# Tag"],
		imgUrl: "",
		skill: [
			"# React.js",
			"# Flask",
			"# uWsgi",
			"# NginX",
			"# MongoDB",
			"# AWS EC2, S3",
			"# Docker",
			"# NLP (Pytorch, KcBert)",
		],
		summaryDescription: "설명입니다.",
		mainDescription: [
			"- 분석 단계 - 요구사항 도출 및 화면 설계",
			"- 설계 단계 - 화면 설계를 통한 자료 사전 및 도메인 정의, ERD작성",
			"- 학습 플랫폼(물음표 학교, 느낌표 학교) 개발",
			"- 나눔 플랫폼(재능기부) 개발",
			"- 강사 관리 시스템 개발",
			"- 통합 예약시스템(징검다리교실) 개발",
			"- 시멘틱(의미 기반) 검색/분석 시스템 구축(Konan Search 솔루션 사용)",
			"- 사용자 권한 별 관리 기능 제공",
			"- 클라이언트 접속 지연시간 튜닝(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		gitLink: "",
	},
	{
		projectName: "DTX",
		service: "의사 진단차트 서비스",
		type: "develop",
		tag: ["# Tag", "# Tag", "# Tag"],
		imgUrl: "",
		skill: [
			"# React.js",
			"# Flask",
			"# uWsgi",
			"# NginX",
			"# MongoDB",
			"# AWS EC2, S3",
			"# Docker",
			"# NLP (Pytorch, KcBert)",
		],
		summaryDescription: "설명입니다.",
		mainDescription: [
			"- 분석 단계 - 요구사항 도출 및 화면 설계",
			"- 설계 단계 - 화면 설계를 통한 자료 사전 및 도메인 정의, ERD작성",
			"- 학습 플랫폼(물음표 학교, 느낌표 학교) 개발",
			"- 나눔 플랫폼(재능기부) 개발",
			"- 강사 관리 시스템 개발",
			"- 통합 예약시스템(징검다리교실) 개발",
			"- 시멘틱(의미 기반) 검색/분석 시스템 구축(Konan Search 솔루션 사용)",
			"- 사용자 권한 별 관리 기능 제공",
			"- 클라이언트 접속 지연시간 튜닝(무거워진 메인/상세 페이지 소스/라이브러리 관리)",
		],
		serviceLink: "",
		gitLink: "",
	},
];
